source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'Locksmith', :exclusive => true do
  pod "Locksmith", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "Locksmith", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end
